language: perl

install:
  - curl https://perl5-alien.github.io/static/travis/install-system-dontpanic.sh | bash -
  - cpanm -n --installdeps .

  # for t/inline*.t tests
  - cpanm -n Inline::C Inline::CPP

  # for tests against Acme::Ford::Prefect::FFI
  - env PERL_ALT_INSTALL=OVERWRITE cpanm Alt::Alien::FFI::System
  - cpanm -n FFI::Platypus
  
  # for Alien::Libbz2
  - cpanm -n Test::CChecker
  
  # for Acme modules
  - cpanm -n Test::Alien
  
  # for ./travis/test-*
  - cpanm -n local::lib
  
  # for upgrade tests
  - git fetch --unshallow

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  # basic test without anything optional installed
  - perl Build.PL
  - ./Build
  - ./Build test verbose=1
  - ./Build install

  # test that installing to a destdir and then moving that dir
  # to the real root works:
  - ./travis/test-destdir.sh

  # test the regression that happened between 0.019 and 0.020 caused
  # by changes to the format of the data in ConfigData.pm
  - bash -x ./travis/test-upgrade.sh '' "d2d6e3782bfdbec14db2c78532122055d2b22401" '' "0.019"
  
  # test that we can move an Alien dist
  - ./travis/install-perl.sh Acme::Alien::DontPanic /tmp/original
  - mv /tmp/original /tmp/moved
  - ./travis/install-perl.sh Acme::Ford::Prefect    /tmp/moved
  
  # test more normal installs
  - ./travis/install-perl.sh Acme::Alien::DontPanic
  - ./travis/install-perl.sh Acme::Ford::Prefect
  - ./travis/install-perl.sh Acme::Ford::Prefect::FFI
  - ./travis/install-perl.sh Alien::Libbz2
  
  # verify still works with optional modules
  - ./Build test verbose=1

env:
  global:
    - PATH=$PATH:$HOME/opt/dontpanic/current/bin
    - LD_LIBRARY_PATH=$HOME/opt/dontpanic/current/lib
    - PKG_CONFIG_PATH=$HOME/opt/dontpanic/current/lib/pkgconfig
  matrix:
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_INSTALL_TYPE=system

sudo: false
